### ISSUE TITLE
Connections forcably closed

### ISSUE THREAD

**Issue by b-kamphorst** [lschoe/mpyc#16]
Dear lschoe,

I've been experiencing very strange MPyC behaviour since Monday. I run the following code with parameter "-M 3":
```
from mpyc.runtime import mpc


async def main():
    async with mpc:
        secnum = mpc.SecFxp()
        a = secnum(2 if mpc.pid == 0 else None)
        a = mpc.input(a, 0)
        print(await mpc.output(a))
        b = 1 / a
        print(await mpc.output(b))


if __name__ == "__main__":
    mpc.run(main())
```

Expected outcome: 
`2.0`
`0.5`

However, the code results in the following error:

```
Traceback (most recent call last):
  File "C:/Users/kamphorstb/git_repositories/CONVINCED/kaplan-meier/scripts/tester.py", line 15, in <module>
    mpc.run(main())
  File "C:\Users\kamphorstb\git_repositories\CONVINCED\kaplan-meier\.venv\lib\site-packages\mpyc\runtime.py", line 161, in run
    return self._loop.run_until_complete(f)
  File "C:\Users\kamphorstb\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 581, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
2020-07-15 14:44:03,707 Start MPyC runtime v0.6.8
2020-07-15 14:44:05,048 All 3 parties connected.
2.0
2020-07-15 14:44:05,075 Exception in callback mpc_coro.<locals>.typed_asyncoro.<locals>.<lambda>(<Task finishe...ut of range')>) at C:\Users\kamphorstb\git_repositories\CONVINCED\kaplan-meier\.venv\lib\site-packages\mpyc\asyncoro.py:387
handle: <Handle mpc_coro.<locals>.typed_asyncoro.<locals>.<lambda>(<Task finishe...ut of range')>) at C:\Users\kamphorstb\git_repositories\CONVINCED\kaplan-meier\.venv\lib\site-packages\mpyc\asyncoro.py:387>
Traceback (most recent call last):
  File "C:\Users\kamphorstb\AppData\Local\Programs\Python\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\kamphorstb\git_repositories\CONVINCED\kaplan-meier\.venv\lib\site-packages\mpyc\asyncoro.py", line 387, in <lambda>
    d.add_done_callback(lambda v: _reconcile(decl, v))
  File "C:\Users\kamphorstb\git_repositories\CONVINCED\kaplan-meier\.venv\lib\site-packages\mpyc\asyncoro.py", line 299, in _reconcile
    givn = givn.result()
  File "C:\Users\kamphorstb\git_repositories\CONVINCED\kaplan-meier\.venv\lib\site-packages\mpyc\asyncoro.py", line 237, in _wrap
    return await coro
  File "C:\Users\kamphorstb\git_repositories\CONVINCED\kaplan-meier\.venv\lib\site-packages\mpyc\asyncoro.py", line 227, in __await__
    val = self.coro.send(None)
  File "C:\Users\kamphorstb\git_repositories\CONVINCED\kaplan-meier\.venv\lib\site-packages\mpyc\runtime.py", line 393, in _recombine
    return thresha.recombine(field, points)
  File "C:\Users\kamphorstb\git_repositories\CONVINCED\kaplan-meier\.venv\lib\site-packages\mpyc\thresha.py", line 79, in recombine
    s = shares[i][h]
IndexError: list index out of range
2020-07-15 14:44:05,085 Task was destroyed but it is pending!
task: <Task pending coro=<_wrap() running at C:\Users\kamphorstb\git_repositories\CONVINCED\kaplan-meier\.venv\lib\site-packages\mpyc\asyncoro.py:237> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000002E001D386A8>()]> cb=[mpc_coro.<locals>.typed_asyncoro.<locals>.<lambda>() at C:\Users\kamphorstb\git_repositories\CONVINCED\kaplan-meier\.venv\lib\site-packages\mpyc\asyncoro.py:387]>
2020-07-15 14:44:05,085 Task was destroyed but it is pending!
```

Running the same code in three terminals (additional parameter "-I x", x = 0, 1, 2) results in similar messages for players 0 and 1. Player 2 instead shows the following:

```
2020-07-15 14:30:25,173 Start MPyC runtime v0.6.8
2020-07-15 14:30:25,574 All 3 parties connected.
2.0
a: <mpyc.sectypes.SecFxp32:16 object at 0x000001753828C548>
f: 16
2020-07-15 14:30:26,047 Exception in callback _SelectorSocketTransport._call_connection_lost(ConnectionRes..., 10054, None))
handle: <Handle _SelectorSocketTransport._call_connection_lost(ConnectionRes..., 10054, None))>
Traceback (most recent call last):
  File "C:\Users\kamphorstb\AppData\Local\Programs\Python\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\kamphorstb\AppData\Local\Programs\Python\Python37\lib\asyncio\selector_events.py", line 926, in _call_connection_lost
    super()._call_connection_lost(exc)
  File "C:\Users\kamphorstb\AppData\Local\Programs\Python\Python37\lib\asyncio\selector_events.py", line 700, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "C:\Users\kamphorstb\git_repositories\CONVINCED\kaplan-meier\.venv\lib\site-packages\mpyc\asyncoro.py", line 125, in connection_lost
    raise exc
  File "C:\Users\kamphorstb\AppData\Local\Programs\Python\Python37\lib\asyncio\selector_events.py", line 814, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2020-07-15 14:30:28,334 Exception in callback _SelectorSocketTransport._call_connection_lost(ConnectionRes..., 10054, None))
handle: <Handle _SelectorSocketTransport._call_connection_lost(ConnectionRes..., 10054, None))>
Traceback (most recent call last):
  File "C:\Users\kamphorstb\AppData\Local\Programs\Python\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\kamphorstb\AppData\Local\Programs\Python\Python37\lib\asyncio\selector_events.py", line 926, in _call_connection_lost
    super()._call_connection_lost(exc)
  File "C:\Users\kamphorstb\AppData\Local\Programs\Python\Python37\lib\asyncio\selector_events.py", line 700, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "C:\Users\kamphorstb\git_repositories\CONVINCED\kaplan-meier\.venv\lib\site-packages\mpyc\asyncoro.py", line 125, in connection_lost
    raise exc
  File "C:\Users\kamphorstb\AppData\Local\Programs\Python\Python37\lib\asyncio\selector_events.py", line 814, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```
Here, the `a: <mpyc.sectypes.SecFxp32:16 object at 0x000001753828C548>` and `f: 16` are print statements that I put in `mpc._rec()`. Players 0 and 1 did not print anything here.

The issue rises in MPyC versions 0.6, 0.6.5, 0.6.7, 0.6.8 (versions where this used to work!) and for various versions of Python 3. It also arises in a Docker environment (kind of ruling out firewall issues). My colleague experiences the same issue on a different workstation.

My colleague later noted that an easier example (which we did not quite investigate as thoroughly) kept running forever:
```
from mpyc.runtime import mpc


async def main():
    async with mpc:
        secnum = mpc.SecFxp()
        a = secnum(2 if mpc.pid == 0 else None)
        a = mpc.input(a, 0)
        print(await mpc.output(a))
        b = a * a  # simpler than 1 / a
        print(await mpc.output(b))


if __name__ == "__main__":
    mpc.run(main())
```

I hope that you can reproduce the issue. If you need any further information I'd be happy to provide that.

**Comment by b-kamphorst** [comment]
@ThomasTNO

**Comment by lschoe** [comment]
OK, thanks, good catch! 
The issue is connected to the use of the integral flag for secure fixed-point numbers. If the integral value 2 is replaced by a nonintegral value 2.5, say, the problem disappears. Alternatively, if you set integral=True or integral=False, like below, the problem also disappears:
 `a = secnum(2 if mpc.pid == 0 else None, integral=True)` or 
 `a = secnum(2 if mpc.pid == 0 else None, integral=False)`

By default for a SecureFixedPoint number the integral bit will be set to True if the value provided is integral. But in this case that only happens for party 0. The other parties will have the integral bit set to None. And then some parties will start running in instance of the mpc.trunc() protocol and party 0 won't and hell breaks loose;)

See also this previous issue [#11](https://github.com/lschoe/mpyc/issues/11). A way out is to disable automatically setting the integral bit, but in many cases that's actually convenient. So, let's rethink this a bit more ...

**Comment by b-kamphorst** [comment]
I really didn't think of that... Which is unfortunate, as I made the very same mistake about a year ago. 

Perhaps it makes more sense to resolve this "issue" in `mpc.input()` rather than in `mpc.SecFxp()`? For example, you could have `mpc.input()` accept an additional keyword argument `reveal_integral_bit` that defaults to False. Then, when a SecretNumber with intregral-attribute is send to mpc.input, to things might happen:

- if `reveal_integral_bit == False` then the integral-attribute of SecretNumber is set to 0 / None. (Perhaps provided `len(self.parties) > 1`.)
- if `reveal_integral_bit == False` then the integral-attribute of SecretNumber is not altered. Instead, it is publicly send along with the shares to the other parties so that they know what their local integral-attribute should be.

Anyhow, thank you for pointing this out and we're happy to join your rethinking :)

**Comment by lschoe** [comment]
Yeah, our immunity against this kind of errors seems to wear off after a while;)

Sending along the (public) integral bit will get a bit messy, especially when there is more than one sender in mpc.input(), which would lead to mixed cases. And explicit control via an extra keyword argument for mpc.input() is also a bit low-level for the average user and would complicate the API for mpc.input() a bit too much I would say.

But I'm starting to think that automatically setting the integral bit to True is maybe not such a good idea after all. The reason to do this is for some efficiency gain. The integral bit is especially effective when working with Boolean values 0.0 and 1.0, but in those cases the MPyC routines already set the integral bit properly (e.g., the secfxp returned by a secure comparison secfxp(a) < secfxp(b) will have its integral bit set to True).

To avoid the issue, it's maybe better to set integral=False as default, even if the value given happens to be integral. If a user is aware of the efficiency gains, and the values happen to be integral, one needs to set the flag integral=True explicitly. Given that the flag has to be set explicitly, this also needs to be done when combined with mpc.input(). The new behavior for the problem examples you gave will be that all parties set integral=False by default. If the parties know that party 0's input will be integral and they want to take advantage of this, then they all add integral=True.

Only advanced users like you would then use the integral flag, while other users need not be aware of it -- and are not affected by it either. Hopefully this idea flies, and has no immediate drawbacks?

**Comment by b-kamphorst** [comment]
Indeed, I had not considered multiple senders. Although this can probably be solved I agree that things get more messy and that this might not be the optimal solution. 

I appreciate the elegance of a default check that sets the integral bit to True, but I guess that such an automatic and under-the-hood feature should never cause the issues that I ran into -- any user could run into this issue. Explicitly opting for integral=True ensures that the user (to some extend) is aware that something has changed, making it slightly easier to find the cause of the issue (even though it is still hard to identify in the not-so-explicit traceback / infinite loop). Moreover, the novel default behaviour can no longer cause the error. I like your suggestion to have this as the default behaviour.

Of course I can not quite predict the effects or potential side-effects in making this change as well as you, but I don't foresee any functionality issues. Just the efficiency loss in specified protocol implementations that do not explicitly set the integral bit, as you mentioned. In my own work, I don't expect any change in efficiency as I heavily utilise the support of non-integer secure numbers. Also, you have quite an extensive testsuite so that should give some confidence in the robustness of this change :)

**Comment by lschoe** [comment]
Agreed. Will try and include the switch to the new default behavior soon.
