### ISSUE TITLE
In the KM survival Jupyter demo I'm seeing an import error

### ISSUE THREAD

**Issue by smspencer** [lschoe/mpyc#6]
on this line:

```
from kmsurvival import fit_plot, events_to_table, events_from_table, logrank_test, aggregate, agg_logrank_test

stark sm_spencer$ cat km_analysis.py 
import os, functools
import pandas as pd
import matplotlib.pyplot as plt
import lifelines.statistics
from mpyc.runtime import mpc
mpc.logging(False)
from kmsurvival import fit_plot, events_to_table, events_from_table, logrank_test, aggregate, agg_logrank_test

print('Hello MPC World')

stark sm_spencer$ python3 km_analysis.py 
Traceback (most recent call last):
  File "km_analysis.py", line 7, in <module>
    from kmsurvival import fit_plot, events_to_table, events_from_table, logrank_test, aggregate, agg_logrank_test
ImportError: cannot import name 'fit_plot' from 'kmsurvival' (/usr/local/lib/python3.7/site-packages/kmsurvival/__init__.py)
stark sm_spencer$ 
```

I took a quick look at the kmsurvival source and didn't see anything named fit_plot... am I missing something?

**Comment by smspencer** [comment]
sorry, the code block should look like so:

```
stark sm_spencer$ cat km_analysis.py 
import os, functools
import pandas as pd
import matplotlib.pyplot as plt
import lifelines.statistics
from mpyc.runtime import mpc
mpc.logging(False)
from kmsurvival import fit_plot, events_to_table, events_from_table, logrank_test, aggregate, agg_logrank_test

print('Hello MPC World')

stark sm_spencer$ python3 km_analysis.py 
Traceback (most recent call last):
  File "km_analysis.py", line 7, in <module>
    from kmsurvival import fit_plot, events_to_table, events_from_table, logrank_test, aggregate, agg_logrank_test
ImportError: cannot import name 'fit_plot' from 'kmsurvival' (/usr/local/lib/python3.7/site-packages/kmsurvival/__init__.py)
stark sm_spencer$ 
```

**Comment by lschoe** [comment]
Looks like you are using the package https://pypi.org/project/kmsurvival/, but here we are using the MPyC demo https://github.com/lschoe/mpyc/blob/master/demos/kmsurvival.py. 

Name clash for kmsurvival is indeed a bit unfortunate. Might rename the MPyC demo kmsurvival.py to something more unique at some point.

**Comment by smspencer** [comment]
Ahhh, that would do it! Thanks for the quick solution.

**Comment by lschoe** [comment]
You’re welcome
